version: "3"
services:
  namenode:
    platform: linux/amd64
    image: apache/hadoop:3.4.1
    hostname: namenode
    command: [ "hdfs", "namenode" ]
    ports:
      - 9870:9870
      - 9000:9000
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
      HADOOP_HOME: "/opt/hadoop"
    volumes:
      - ../src/:/src/
      - "/Users/a.sashina/IdeaProjects/data-processing/data/big.txt:/tmp/data/big.txt"
      - "/Users/a.sashina/IdeaProjects/data-processing/data/web-Google.txt:/tmp/data/web-Google.txt"

  datanode1:
    platform: linux/amd64
    image: apache/hadoop:3.4.1
    command: [ "hdfs", "datanode" ]
    env_file:
      - ./config
    environment:
      HADOOP_HOME: "/opt/hadoop"
    volumes:
      - ../src/:/src/

  datanode2:
    platform: linux/amd64
    image: apache/hadoop:3.4.1
    command: [ "hdfs", "datanode" ]
    env_file:
      - ./config
    environment:
      HADOOP_HOME: "/opt/hadoop"
    volumes:
      - ../src/:/src/

  resourcemanager:
    platform: linux/amd64
    image: apache/hadoop:3.4.1
    hostname: resourcemanager
    command: [ "yarn", "resourcemanager" ]
    ports:
      - 8088:8088
    env_file:
      - ./config
    environment:
      HADOOP_HOME: "/opt/hadoop"
    volumes:
      - ../src/:/src/

  nodemanager:
    platform: linux/amd64
    image: apache/hadoop:3.4.1
    command: [ "yarn", "nodemanager" ]
    env_file:
      - ./config
    environment:
      HADOOP_HOME: "/opt/hadoop"
    volumes:
      - ../src/:/src/

  spark-master:
    image: bitnami/spark:3.2.4
    environment:
      JDK_JAVA_OPTIONS: --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
      SPARK_MODE: master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - "./spark-logs:/spark/logs"
      - "./data/Books_rating.csv:/Users/a.sashina/IdeaProjects/data-processing/data/Books_rating.csv"
      - "./data/books_data.csv:/Users/a.sashina/IdeaProjects/data-processing/data/books_data.csv"

  spark-worker-1:
    image: bitnami/spark:3.2.4
    depends_on:
      - spark-master
    environment:
      JDK_JAVA_OPTIONS: --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - "./spark-logs:/spark/logs"
      - "./data/Books_rating.csv:/Users/a.sashina/IdeaProjects/data-processing/data/Books_rating.csv"
      - "./data/books_data.csv:/Users/a.sashina/IdeaProjects/data-processing/data/books_data.csv"

  spark-worker-2:
    image: bitnami/spark:3.2.4
    depends_on:
      - spark-master
    environment:
      JDK_JAVA_OPTIONS: --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - "./spark-logs:/spark/logs"
      - "./data/Books_rating.csv:/Users/a.sashina/IdeaProjects/data-processing/data/Books_rating.csv"
      - "./data/books_data.csv:/Users/a.sashina/IdeaProjects/data-processing/data/books_data.csv"

  spark-worker-3:
    image: bitnami/spark:3.2.4
    depends_on:
      - spark-master
    environment:
      JDK_JAVA_OPTIONS: --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    volumes:
      - "./spark-logs:/spark/logs"
      - "./data/Books_rating.csv:/Users/a.sashina/IdeaProjects/data-processing/data/Books_rating.csv"
      - "./data/books_data.csv:/Users/a.sashina/IdeaProjects/data-processing/data/books_data.csv"